# NUM_OF_USERS_IN_DB = 15
# USER_ID_TO_TEST_1 = "U02"
# USER_ID_TO_TEST_2 = "U11"
# USER_NAME_TO_TEST_1 = "Steve,Job"
# USER_PHONE_TO_TEST_1 = 879123456
# USER_LOC_TO_TEST_1 ="Idaho"
# USER_TIMEZONE_TO_TEST_1 = "PST"
# USER_LINKED_TO_TEST_1 = "https://www.linkedin.com/in/Steve Job/"
#INVALID_USERID = "A@12xy"
# MAX_USER_ID = "U30"
# AUTO_GEN_ID = "U31"

INVALID_USER = "welcome"
INVALID_PWD = "abc"

VALID_USERSKILLID_2 ="US120"
USER_ID_2 = "U07"
SKILL_ID_2 = 1
MONTHS_OF_EXP_2 = 10

VALID_USERSKILLID_3 ="US111"
USER_ID_3 = "U08"
SKILL_ID_3 = 4
MONTHS_OF_EXP_3 = 58
INVAD_MONTHS_OF_EXP_4 = "abc123"

VALID_USERSKILLID = "US134"
USER_ID = "U03"
SKILL_ID = 5
MONTHS_OF_EXP = 20
INVALID_USERSKILLID = "US1000"
MAX_USER_SKILL_ID = "US137"
AUTO_GEN_USER_SKILL_ID ="US138"
VALID_USERSKILLID_5= "US126"

